name: Deploy byban94/web to Apache

on:
  workflow_dispatch: # arba naudok push, jei nori automatikos

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      # Checkout tavo privatu web repo
      - name: Checkout web repo
        uses: actions/checkout@v4
        with:
          repository: byban94/web
          ref: main
          path: web-src
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      # Ištrink senus failus ir nukopijuok naujus su visais pavadinimais
      - name: Deploy web files
        run: |
          sudo rm -rf /var/www/html/*
          sudo cp -r web-src/* /var/www/html/
          sudo chown -R apache:apache /var/www/html/
