name: Deploy to Homelab

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: sudo dnf install -y httpd
      - name: Deploy web page
        run: |
          echo "Automatinis diegimas veikia!" | sudo tee /var/www/html/index.html
          sudo systemctl enable --now httpd
